name: main-workflow
on: 
  pull_request:
  push:
    branches: 
      - main
jobs:
  dockerfile-linter:
    name: "Main Dockerfile linter job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout our code"
        uses: actions/checkout@v7
      - name: "Docker linter"
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  python-linter:
    name: "Main Python linter job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout our code"
        uses: actions/checkout@v7
      - name: "Use Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: "Install Python linter"
        run: "pip install -r requirements-dev.txt -r requirements.txt"
      - name: "Run Python linter"
        run: "pylint main.py"
  build-and-push:
    name: "Build and Push container to registry"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Registry login"
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: "Extract image metadata"
        id: metadata
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/tyronvergara/mini-api
      - name: "Push container image"
        uses: docker/build-push-action@v7
        with:
          context: "."
          push: true
          tags: ${{steps.metadata.outputs.tags}}
          labels: ${{steps.metadata.outputs.labels}}

